### PR TITLE
Add json files with questions

### PR DESCRIPTION
**Pull request by ARenzDev**
The incorporation of these files contributes to the project by introducing a specific set of questions in a structured and readable format. This change may be part of expanding the project's question database, enhancing the variety of content, or introducing new features related to questions. The inclusion of JSON files facilitates the manipulation and management of questions within the code, allowing greater flexibility and ease of project maintenance.

### CODE REVIEW

**Comment by YoelFerreyra** [comment]
The changes look good

**Comment by ARenzDev** [comment]
image

added the following files to this branch

@YoelFerreyra @Israel-Laguan

**Comment by Israel-Laguan** [comment]
Please check some questions without a proper UUID, then some questions that are not really asking anythin

**Comment by ARenzDev** [comment]
check @Israel-Laguan @YoelFerreyra  I corrected some uuid

**Pull request merged**
